FROM bellsoft/liberica-openjdk-alpine:latest

ENV SPARK_HOME=/usr/lib/python3.8/site-packages/pyspark

RUN apk add bash && \
  apk add nano && \
  apk add postgresql-client && \
  apk add python3 && \
  pip3 install --upgrade pip && \
  pip3 install pyspark && \
  pip3 install pytest && \
  ln /usr/bin/python3.8 /usr/bin/python

WORKDIR /src

COPY . /src
